FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    g++ cmake make ca-certificates binutils libx11-dev uuid-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /src
